// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: AssignTeammateService.proto

package generatedfiles

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssignTeamMateClient is the client API for AssignTeamMate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssignTeamMateClient interface {
	// Sends a greeting
	AssignTeamMate(ctx context.Context, in *AssignTeamRequestgRPC, opts ...grpc.CallOption) (*AssignTeamResponsegRPC, error)
}

type assignTeamMateClient struct {
	cc grpc.ClientConnInterface
}

func NewAssignTeamMateClient(cc grpc.ClientConnInterface) AssignTeamMateClient {
	return &assignTeamMateClient{cc}
}

func (c *assignTeamMateClient) AssignTeamMate(ctx context.Context, in *AssignTeamRequestgRPC, opts ...grpc.CallOption) (*AssignTeamResponsegRPC, error) {
	out := new(AssignTeamResponsegRPC)
	err := c.cc.Invoke(ctx, "/AssignTeamMate/AssignTeamMate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssignTeamMateServer is the server API for AssignTeamMate service.
// All implementations must embed UnimplementedAssignTeamMateServer
// for forward compatibility
type AssignTeamMateServer interface {
	// Sends a greeting
	AssignTeamMate(context.Context, *AssignTeamRequestgRPC) (*AssignTeamResponsegRPC, error)
	mustEmbedUnimplementedAssignTeamMateServer()
}

// UnimplementedAssignTeamMateServer must be embedded to have forward compatible implementations.
type UnimplementedAssignTeamMateServer struct {
}

func (UnimplementedAssignTeamMateServer) AssignTeamMate(context.Context, *AssignTeamRequestgRPC) (*AssignTeamResponsegRPC, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTeamMate not implemented")
}
func (UnimplementedAssignTeamMateServer) mustEmbedUnimplementedAssignTeamMateServer() {}

// UnsafeAssignTeamMateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssignTeamMateServer will
// result in compilation errors.
type UnsafeAssignTeamMateServer interface {
	mustEmbedUnimplementedAssignTeamMateServer()
}

func RegisterAssignTeamMateServer(s grpc.ServiceRegistrar, srv AssignTeamMateServer) {
	s.RegisterService(&AssignTeamMate_ServiceDesc, srv)
}

func _AssignTeamMate_AssignTeamMate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTeamRequestgRPC)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignTeamMateServer).AssignTeamMate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AssignTeamMate/AssignTeamMate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignTeamMateServer).AssignTeamMate(ctx, req.(*AssignTeamRequestgRPC))
	}
	return interceptor(ctx, in, info, handler)
}

// AssignTeamMate_ServiceDesc is the grpc.ServiceDesc for AssignTeamMate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssignTeamMate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AssignTeamMate",
	HandlerType: (*AssignTeamMateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignTeamMate",
			Handler:    _AssignTeamMate_AssignTeamMate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AssignTeammateService.proto",
}
